export const countries = [
  {
    id: 1,
    name: "Afghanistan",
    nativeName: "افغانستان",
    population: 27657145,
    region: "Asia",
    subRegion: "Southern Asia",
    capital: "Kabul",
    topLevelDomain: ".af",
    currencies: ["Afghan Afghani"],
    languages: ["Pashto", "Dari"],
    borderCountries: [
      "Iran",
      "Pakistan",
      "Turkmenistan",
      "Uzbekistan",
      "Tajikistan",
      "China",
    ],
    flag: "https://flagcdn.com/w320/af.png",
  },
  {
    id: 2,
    name: "Armenia",
    nativeName: "Հայաստան",
    population: 2994400,
    region: "Asia",
    subRegion: "Western Asia",
    capital: "Yerevan",
    topLevelDomain: ".am",
    currencies: ["Armenian Dram"],
    languages: ["Armenian"],
    borderCountries: [
      "Georgia",
      "Azerbaijan",
      "Iran",
      "Turkey",
    ],
    flag: "https://flagcdn.com/w320/am.png",
  },
  {
    id: 3,
    name: "Azerbaijan",
    nativeName: "Azərbaycan",
    population: 9730500,
    region: "Asia",
    subRegion: "Western Asia",
    capital: "Baku",
    topLevelDomain: ".az",
    currencies: ["Azerbaijani Manat"],
    languages: ["Azerbaijani"],
    borderCountries: [
      "Russia",
      "Georgia",
      "Armenia",
      "Iran",
      "Turkey",
    ],
    flag: "https://flagcdn.com/w320/az.png",
  },
  {
    id: 4,
    name: "Bahrain",
    nativeName: "البحرين",
    population: 1404900,
    region: "Asia",
    subRegion: "Western Asia",
    capital: "Manama",
    topLevelDomain: ".bh",
    currencies: ["Bahraini Dinar"],
    languages: ["Arabic"],
    borderCountries: [],
    flag: "https://flagcdn.com/w320/bh.png",
  },
  {
    id: 5,
    name: "Bangladesh",
    nativeName: "বাংলাদেশ",
    population: 161006790,
    region: "Asia",
    subRegion: "Southern Asia",
    capital: "Dhaka",
    topLevelDomain: ".bd",
    currencies: ["Bangladeshi Taka"],
    languages: ["Bengali"],
    borderCountries: ["India", "Myanmar"],
    flag: "https://flagcdn.com/w320/bd.png",
  },
  {
    id: 6,
    name: "Bhutan",
    nativeName: "འབྲུག་ཡུལ",
    population: 775620,
    region: "Asia",
    subRegion: "Southern Asia",
    capital: "Thimphu",
    topLevelDomain: ".bt",
    currencies: ["Bhutanese Ngultrum"],
    languages: ["Dzongkha"],
    borderCountries: ["China", "India"],
    flag: "https://flagcdn.com/w320/bt.png",
  },
  {
    id: 7,
    name: "Brunei",
    nativeName: "Negara Brunei Darussalam",
    population: 411900,
    region: "Asia",
    subRegion: "South-Eastern Asia",
    capital: "Bandar Seri Begawan",
    topLevelDomain: ".bn",
    currencies: ["Brunei Dollar"],
    languages: ["Malay"],
    borderCountries: ["Malaysia"],
    flag: "https://flagcdn.com/w320/bn.png",
  },
  {
    id: 8,
    name: "Cambodia",
    nativeName: "Kâmpŭchéa",
    population: 15626444,
    region: "Asia",
    subRegion: "South-Eastern Asia",
    capital: "Phnom Penh",
    topLevelDomain: ".kh",
    currencies: ["Cambodian Riel"],
    languages: ["Khmer"],
    borderCountries: [
      "Thailand",
      "Laos",
      "Vietnam",
    ],
    flag: "https://flagcdn.com/w320/kh.png",
  },
  {
  id: 9,
  name: "China",
  nativeName: "中国",
  population: 1402112000,
  region: "Asia",
  subRegion: "Eastern Asia",
  capital: "Beijing",
  topLevelDomain: ".cn",
  currencies: ["Chinese Yuan"],
  languages: ["Chinese"],
  borderCountries: [
    "Afghanistan",
    "Bhutan",
    "India",
    "Kazakhstan",
    "Kyrgyzstan",
    "Laos",
    "Mongolia",
    "Myanmar",
    "Nepal",
    "North Korea",
    "Pakistan",
    "Russia",
    "Tajikistan",
    "Vietnam"
  ],
  flag: "https://flagcdn.com/w320/cn.png",
},
{
  id: 10,
  name: "Cyprus",
  nativeName: "Κύπρος",
  population: 1207000,
  region: "Asia",
  subRegion: "Western Asia",
  capital: "Nicosia",
  topLevelDomain: ".cy",
  currencies: ["Euro"],
  languages: ["Greek", "Turkish"],
  borderCountries: [],
  flag: "https://flagcdn.com/w320/cy.png",
},
{
  id: 11,
  name: "Georgia",
  nativeName: "საქართველო",
  population: 3720400,
  region: "Asia",
  subRegion: "Western Asia",
  capital: "Tbilisi",
  topLevelDomain: ".ge",
  currencies: ["Georgian Lari"],
  languages: ["Georgian"],
  borderCountries: ["Armenia", "Azerbaijan", "Russia", "Turkey"],
  flag: "https://flagcdn.com/w320/ge.png",
},
{
  id: 12,
  name: "India",
  nativeName: "भारत",
  population: 1428000000,
  region: "Asia",
  subRegion: "Southern Asia",
  capital: "New Delhi",
  topLevelDomain: ".in",
  currencies: ["Indian Rupee"],
  languages: ["Hindi", "English"],
  borderCountries: [
    "Bangladesh",
    "Bhutan",
    "China",
    "Myanmar",
    "Nepal",
    "Pakistan"
  ],
  flag: "https://flagcdn.com/w320/in.png",
},
{
  id: 13,
  name: "Indonesia",
  nativeName: "Indonesia",
  population: 277500000,
  region: "Asia",
  subRegion: "South-Eastern Asia",
  capital: "Jakarta",
  topLevelDomain: ".id",
  currencies: ["Indonesian Rupiah"],
  languages: ["Indonesian"],
  borderCountries: ["Malaysia", "Papua New Guinea", "Timor-Leste"],
  flag: "https://flagcdn.com/w320/id.png",
},
{
  id: 14,
  name: "Iran",
  nativeName: "ایران",
  population: 89172000,
  region: "Asia",
  subRegion: "Southern Asia",
  capital: "Tehran",
  topLevelDomain: ".ir",
  currencies: ["Iranian Rial"],
  languages: ["Persian"],
  borderCountries: [
    "Afghanistan",
    "Armenia",
    "Azerbaijan",
    "Iraq",
    "Pakistan",
    "Turkey",
    "Turkmenistan"
  ],
  flag: "https://flagcdn.com/w320/ir.png",
},
{
  id: 15,
  name: "Iraq",
  nativeName: "العراق",
  population: 45500000,
  region: "Asia",
  subRegion: "Western Asia",
  capital: "Baghdad",
  topLevelDomain: ".iq",
  currencies: ["Iraqi Dinar"],
  languages: ["Arabic", "Kurdish"],
  borderCountries: [
    "Iran",
    "Jordan",
    "Kuwait",
    "Saudi Arabia",
    "Syria",
    "Turkey"
  ],
  flag: "https://flagcdn.com/w320/iq.png",
},
{
  id: 16,
  name: "Israel",
  nativeName: "ישראל",
  population: 9800000,
  region: "Asia",
  subRegion: "Western Asia",
  capital: "Jerusalem",
  topLevelDomain: ".il",
  currencies: ["Israeli New Shekel"],
  languages: ["Hebrew", "Arabic"],
  borderCountries: ["Egypt", "Jordan", "Lebanon", "Syria"],
  flag: "https://flagcdn.com/w320/il.png",
},
{
  id: 17,
  name: "Japan",
  nativeName: "日本",
  population: 123000000,
  region: "Asia",
  subRegion: "Eastern Asia",
  capital: "Tokyo",
  topLevelDomain: ".jp",
  currencies: ["Japanese Yen"],
  languages: ["Japanese"],
  borderCountries: [],
  flag: "https://flagcdn.com/w320/jp.png",
},
{
  id: 18,
  name: "Jordan",
  nativeName: "الأردن",
  population: 11300000,
  region: "Asia",
  subRegion: "Western Asia",
  capital: "Amman",
  topLevelDomain: ".jo",
  currencies: ["Jordanian Dinar"],
  languages: ["Arabic"],
  borderCountries: ["Iraq", "Israel", "Saudi Arabia", "Syria"],
  flag: "https://flagcdn.com/w320/jo.png",
},
{
  id: 19,
  name: "Kazakhstan",
  nativeName: "Қазақстан",
  population: 20300000,
  region: "Asia",
  subRegion: "Central Asia",
  capital: "Astana",
  topLevelDomain: ".kz",
  currencies: ["Kazakhstani Tenge"],
  languages: ["Kazakh", "Russian"],
  borderCountries: [
    "Russia",
    "China",
    "Kyrgyzstan",
    "Uzbekistan",
    "Turkmenistan"
  ],
  flag: "https://flagcdn.com/w320/kz.png",
},
{
  id: 20,
  name: "Uzbekistan",
  nativeName: "Oʻzbekiston",
  population: 38000000,
  region: "Asia",
  subRegion: "Central Asia",
  capital: "Tashkent",
  topLevelDomain: ".uz",
  currencies: ["Uzbekistani So'm"],
  languages: ["Uzbek"],
  borderCountries: [
    "Kazakhstan",
    "Kyrgyzstan",
    "Tajikistan",
    "Afghanistan",
    "Turkmenistan"
  ],
  flag: "https://flagcdn.com/w320/uz.png",
},
];

